// Generated by Wrangler: npx wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts
/// <reference path="./env.d.ts" />

interface CloudflareEnv {
	ENVIRONMENT: string;
	BUCKET: R2Bucket;
	DB: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
