/**
 * 검색 동의어 그룹. 같은 그룹의 단어는 서로 확장 검색된다.
 * 항목은 소문자로 적고, 띄어쓰기가 있는 표현은 비교 시 공백을 제거한 형태로도 매칭된다.
 */
export const SYNONYM_GROUPS: string[][] = [
    ['서포트', '써포트', '지지대', 'support', 'supports'],
    ['fdm', 'fff', '필라멘트', 'filament', '용융적층', '용융 적층'],
    ['sla', '광조형', '레진', 'resin'],
    ['dlp', '레진', 'resin', 'msla'],
    ['견적', '가격', '비용', '요금', '단가', '얼마', 'quote', 'price', 'pricing', 'cost'],
    ['출력', '프린팅', '프린트', '인쇄', 'printing', 'print'],
    ['출력대행', '출력 대행', '프린팅대행', '프린팅 대행', '외주'],
    ['stl', '스틸', '에스티엘'],
    ['step', 'stp', '스텝'],
    ['인필', '내부채움', '내부 채움', '채움률', 'infill'],
    ['후가공', '후처리', '도색', '도장', '사포', '샌딩', 'post-processing', 'postprocessing', 'finishing', 'sanding', 'painting'],
    ['납기', '제작기간', '제작 기간', '수령', '배송', '소요시간', '소요 시간', 'turnaround', 'delivery', 'leadtime', 'lead time', 'shipping'],
    ['시제품', '프로토타입', '프로토 타입', '목업', 'prototype', 'prototyping', 'mockup', 'mock-up'],
    ['피규어', '미니어처', '모형', 'figure', 'figurine', 'miniature'],
    ['투명', '클리어', 'clear', 'transparent'],
    ['내열', '고온', 'heat-resistant', 'heat resistant', 'heat'],
    ['내충격', '충격', 'impact', 'impact-resistant'],
    ['pla', '피엘에이'],
    ['abs', '에이비에스'],
    ['petg', '펫지', '페트지'],
    ['tpu', '플렉서블', '유연', '말랑', 'flexible', 'rubber'],
    ['나일론', 'nylon'],
    ['캡스톤', '캡스톤디자인', '캡스톤 디자인', 'capstone'],
    ['졸업작품', '졸업 작품', '졸작', 'graduation'],
    ['사진', '이미지', '사진으로', 'photo', 'image', 'picture'],
    ['모델링', '3d모델', '3d 모델', 'modeling', 'modelling'],
    ['공차', '유격', '치수', 'tolerance', 'clearance', 'dimension'],
    ['벽두께', '벽 두께', '두께', 'wall thickness', 'thickness'],
    ['케이스', '하우징', '외장', 'housing', 'case', 'enclosure'],
    ['제작센터', '메이커스페이스', '찾아오는길', '찾아오는 길', '오시는길', '오시는 길', '위치', 'makerspace', 'location', 'directions'],
    ['주문', '결제', '구매', 'order', 'checkout', 'purchase'],
    ['3d프린터', '프린터', '장비', 'printer', 'hardware'],
    ['분할', '분할출력', '분할 출력', 'split', 'splitting'],
    ['오류', '에러', '깨짐', 'error', 'errors'],
    ['소재', '재료', '재질', 'material', 'materials'],
    ['문의', '상담', '연락', 'contact', 'inquiry'],
    ['환불', '취소', 'refund', 'cancel', 'cancellation'],
    ['레이어', '적층', 'layer'],
]
